"""initial schema

Revision ID: 84229ebad380
Revises: 
Create Date: 2026-03-22 17:10:38.898514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84229ebad380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidad',
    sa.Column('id_localidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_localidad')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(), nullable=True),
    sa.Column('ediciones_ultimos_dos_dias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('configuracion_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('departamento',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo_publicacion', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('ambientes', sa.Integer(), nullable=False),
    sa.Column('dormitorios', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Integer(), nullable=False),
    sa.Column('superficie', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('rol_inmo_dir', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_localidad'], ['localidad.id_localidad'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_table('coordenadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_departamento')
    )
    op.create_table('favorito',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('fecha_agregado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.create_table('foto',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('url_foto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('id_usuario_calificador', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('fecha_calificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_usuario_calificador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario_receptor', sa.Integer(), nullable=False),
    sa.Column('tipo_notificacion', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('id_departamento_ref', sa.Integer(), nullable=True),
    sa.Column('id_resena_ref', sa.Integer(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento_ref'], ['departamento.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_resena_ref'], ['resena.id_resena'], ),
    sa.ForeignKeyConstraint(['id_usuario_receptor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('resena')
    op.drop_table('foto')
    op.drop_table('favorito')
    op.drop_table('coordenadas')
    op.drop_table('departamento')
    op.drop_table('configuracion_usuario')
    op.drop_table('usuario')
    op.drop_table('localidad')
    # ### end Alembic commands ###
